### ISSUE TITLE
Japanese translation for apparel and weapons

### ISSUE THREAD

**Issue by sumghai** [sumghai/Hamefura#1]
@Proxyer, would you be able to provide translations for the following files?:

* [Languages/Japanese/DefInjected/ThingDef/Apparel_Hamefura.xml](https://github.com/sumghai/Hamefura/blob/master/Languages/Japanese/DefInjected/ThingDef/Apparel_Hamefura.xml)
* [Languages/Japanese/DefInjected/ThingDef/WeaponsMelee_Hamefura.xml](https://github.com/sumghai/Hamefura/blob/master/Languages/Japanese/DefInjected/ThingDef/WeaponsMelee_Hamefura.xml)
* [Languages/Japanese/Keyed/Hamefura.xml](https://github.com/sumghai/Hamefura/blob/master/Languages/Japanese/Keyed/Hamefura.xml)

For context, the apparel and weapons are from the [Hamefura](https://ja.wikipedia.org/wiki/%E4%B9%99%E5%A5%B3%E3%82%B2%E3%83%BC%E3%83%A0%E3%81%AE%E7%A0%B4%E6%BB%85%E3%83%95%E3%83%A9%E3%82%B0%E3%81%97%E3%81%8B%E3%81%AA%E3%81%84%E6%82%AA%E5%BD%B9%E4%BB%A4%E5%AC%A2%E3%81%AB%E8%BB%A2%E7%94%9F%E3%81%97%E3%81%A6%E3%81%97%E3%81%BE%E3%81%A3%E3%81%9F%E2%80%A6) franchise (乙女ゲームの破滅フラグしかない悪役令嬢に転生してしまった…)

**Comment by Proxyer** [comment]
I bought all the comics of this work and watched the animation, so I was able to translate it without any problems.

I thought it was difficult to understand the character in the explanation of the clothes, so I added the character name enclosed in parentheses at the end of the sentence. Please consider.
