### ISSUE TITLE
Issue with hamefura, hair modding plus and [cat] show hair or hide all hats

### ISSUE THREAD

**Issue by Chunnyluny** [sumghai/Hamefura#4]
**Describe the bug:**  

Also I'm using show hairs or hide all hats the one from cat.  This error occurred when I used the character editor, I don't like it when pawns are bald so I gave him hair with character editor (turtle) I choose Keith hair, recently I added vanilla hairs retextured from Neronix. so when testing with vanilla hair and putting on tuque or war mask the hair reverted to vanilla hair which was not HD. I have 1 pawn from another savegame also having keith hair, but his hair is showing up normal, he is wearing an vanilla bowler hat. Turtle was wearing war mask so I think it has to do something with the texture, when unequipping war mask his hamefura hair was back. I have posted this to hair modding plus GitHub, show hair or hide hats from Cat so 3 mods are involved. I also have tried to replicate this problem in quicktest, and the problem turned from vanilla hair with hat into transparant hat, which is know behaviour I guess. Earlier I had an error where easy extra apparel layers was the issue, where it says exception drawing overhead layer, so I removed that mod. in the settings show hair I have looked at the settings of warmask. now trying again, the hat is normal showing on the hair with hamefura hair. than testing again with cosplay hair and headgear of cosplay, when drafted it is set to show hair and the hat is also shown, the default is also on show hair but no hat is shown. Now I'm not even sure if it is the savegame. veil and warmask are the issues I having again, tried with glasses and veil and both don't show up. only when drafted, I think the option are or or and not or and. default and drafted cannot be the same options? but when drafted and vanilla hair, sunglasses and veil are showing up. I'm confused. I have 3 save games 1 which is oldest and anything works as intended, the testing faction and the colony of recyclers, the colony or recyclers had the issue. also disabled only apply to colonists because when I put on bunny ears on visitor guest from hospitality the pawn was bald instead of having bunny ears. when I disabled the function the pawn had bunny ears. when in the colony of recyclers I spawned trade caravan having the option on apply to colonist the head are all bald under their headwear.  
![Screenshot 2023-05-20 171720](https://github.com/sumghai/Hamefura/assets/102756485/df5f7df5-143a-470d-8ac0-8a97d9cb3784)

**Expected behavior:**  
 I think when wearing war mask horns are rendered instead of war mask I have checked the settings from show hair or hide all hats. this screenshot is how it should work as intended pawn is wearing tuque with hair from roo hd hairstyle. and glasses from vanilla expanded apparel accessoires. Here it is working normal as intended
![image](https://github.com/sumghai/Hamefura/assets/102756485/65482072-fa4b-4d91-9622-a9f14c02693d)
![Screenshot 2023-05-20 161346](https://github.com/sumghai/Hamefura/assets/102756485/b00e7354-d46a-4a8b-8a4c-0a00e641ff71) when trying again with vanilla hair and warmask it shows like this ![image](https://github.com/sumghai/Hamefura/assets/102756485/894401f1-4ae5-43af-9c73-321032a32ef4)

**Steps to reproduce:**  

1. use character editor and mods including hamefura, hairmoddingplus, show hair or hide all hats, vanilla hair rextured from neronix
2. trying to have a pawn that is bald giving him hair and put on warmask or tuque or veil
3. putting on the options don't shave your hair hair, and apply to colonist off.
4. using my modlist and try to do it with guest visitor with warmask

**Additional information:**
 
 
![error rimpy analyzer hair rendering](https://github.com/sumghai/Hamefura/assets/102756485/0f778851-af94-462c-b0d7-69f5cecd20bb) ![image](https://github.com/sumghai/Hamefura/assets/102756485/8996a47c-d081-4acb-8209-b6635bdb43ff)

 

## System and Game Configuration
**Operating System:**  windows 11
**Physical RAM:**  16GB
**RimWorld base game version:**   1.4.3704 rev874 in config it says rev 866
**RimWorld DLCs loaded:**  none
**Hamefura mod version:**  v.1.1.1
**Hamefura mod downloaded from:**  from steam
**Your mod list:**  rentry https://rentry.co/579q2  

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Hamefura and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Hamefura
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Hamefura is disabled hair modding plus is involved. So I need to disable both
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
This is an issue between Hair Modding Plus and Show Hair With Hats in general, not specific to Hamefura.

Nothing I can do about it.

**Comment by Chunnyluny** [comment]
okay thank you for the reply hope the hairmodding plus and cat show hair or hide all hats have some information for me than.
